### ISSUE TITLE
LUA error on log in with Tinkertoolbox

### ISSUE THREAD

**Issue by Dimmnn** [Azilroka/ElvUI_TinkerToolbox#2]
Screenshot
https://i.imgur.com/PVKNNMK.jpeg

8x ...ce/AddOns/ElvUI_TinkerToolbox/Modules/BagFilters.lua:140: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/ElvUI_TinkerToolbox/Modules/BagFilters.lua"]:140: in function `CacheBagItems'
[string "@Interface/AddOns/ElvUI_TinkerToolbox/Modules/BagFilters.lua"]:395: in function `?'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...vUI/Libraries/Core/Ace/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by nihilistzsche** [comment]
Is this on retail or classic?

**Comment by Dimmnn** [comment]
Retail

**Comment by nihilistzsche** [comment]
Can you recheck with the latest alphas? I believe this should have been fixed already.
